import { PersonalHead } from '@/components/head'
import './globals.css'
import type { Metadata } from 'next'
import { Head } from 'next/document'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <PersonalHead />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
